# Generated by Django 4.1.7 on 2023-03-09 13:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("team_image", models.ImageField(default="default.jpg", upload_to="")),
                ("team_name", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "team_position",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("team_phone", models.CharField(blank=True, max_length=50, null=True)),
                ("team_email", models.CharField(blank=True, max_length=80, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("message", models.TextField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                ("image", models.ImageField(default="default.jpg", upload_to="")),
                ("title", models.CharField(max_length=100)),
                ("writer", models.CharField(max_length=100)),
                ("describes", models.TextField(max_length=50000)),
                (
                    "img2",
                    models.ImageField(
                        blank=True, default="default.jpg", null=True, upload_to=""
                    ),
                ),
                ("t2", models.CharField(blank=True, max_length=100, null=True)),
                ("w2", models.CharField(blank=True, max_length=100, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
            ],
        ),
    ]
