# Generated by Django 4.1.7 on 2023-03-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Read",
        ),
    ]
