# Generated by Django 4.1.7 on 2023-04-24 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="home2",
            old_name="c2",
            new_name="created2",
        ),
    ]
