# Generated by Django 4.1.7 on 2023-03-10 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BlogApp", "0002_home_d2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="d2",
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
    ]
